# Generated by Django 5.2.13 on 2026-04-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='auteur_biographie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livre',
            name='auteur_photo',
            field=models.ImageField(blank=True, null=True, upload_to='authors/'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
