# Generated by Django 5.2.13 on 2026-04-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_livre_auteur_biographie_livre_auteur_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='debloque_par_admin',
            field=models.BooleanField(default=False, help_text="Permet à l'admin de gracier un blocage automatique"),
        ),
    ]
