# Generated by Django 5.2.13 on 2026-04-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_debloque_par_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='statut',
            field=models.CharField(choices=[('demande', 'En attente de validation'), ('en_cours', 'Emprunt actif'), ('rendu', 'Livre retourné'), ('refuse', 'Demande refusée')], default='demande', max_length=20),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='date_retour_prevue',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
