# Generated by Django 5.2.13 on 2026-05-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_emprunt_statut_alter_emprunt_date_retour_prevue'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='duree_choisie',
            field=models.CharField(choices=[('mensuel', 'Mensuel'), ('annuel', 'Annuel')], default='mensuel', max_length=10),
        ),
    ]
