# Generated by Django 5.2.13 on 2026-05-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0006_auteur_livre_auteur_fk_avis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddIndex(
            model_name='emprunt',
            index=models.Index(fields=['statut'], name='core_emprun_statut_febe01_idx'),
        ),
        migrations.AddIndex(
            model_name='emprunt',
            index=models.Index(fields=['date_emprunt'], name='core_emprun_date_em_cd8943_idx'),
        ),
        migrations.AddIndex(
            model_name='emprunt',
            index=models.Index(fields=['est_retourne'], name='core_emprun_est_ret_c3eacf_idx'),
        ),
        migrations.AddIndex(
            model_name='livre',
            index=models.Index(fields=['isbn'], name='core_livre_isbn_6fd05d_idx'),
        ),
        migrations.AddIndex(
            model_name='livre',
            index=models.Index(fields=['titre'], name='core_livre_titre_38a0c0_idx'),
        ),
        migrations.AddIndex(
            model_name='livre',
            index=models.Index(fields=['a_version_numerique'], name='core_livre_a_versi_71d15a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='core_user_usernam_e8adca_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='core_user_role_73872d_idx'),
        ),
    ]
